### ISSUE TITLE
fix test failures for Agentic RAG recipe

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-community/granite-snack-cookbook#36]

**Comment by adampingel** [comment]
FYI @fayvor and @rawkintrevo

**Comment by fayvor** [comment]
@AnnaGutowska I can probably help with this. Can you tell me which version of Python you are using to get this to run successfully? It fails with Python 3.10.12 and 3.10.15.

**Comment by AnnaGutowska** [comment]
Hi @fayvor, I am able to run it locally with Python 3.11.9 as well as on Colab without any errors (granted that the user inputs their api key and project id where instructed)

**Comment by fayvor** [comment]
@AnnaGutowska I think it may pass sometimes on Colab if the libraries are installed in a certain order. Once I get it to run, I can specify a version range for the faulty package.

**Comment by fayvor** [comment]
@AnnaGutowska I was able to get Agentic_RAG to run on Colab (and use the Colab secrets) with these changes:
https://github.com/ibm-granite-community/granite-snack-cookbook/pull/45

**Comment by AnnaGutowska** [comment]
Great, thank you so much! @fayvor I see the tests fail at the authentication step now and not at the package imports anymore.

**Comment by fayvor** [comment]
No problem! Yes, we'll need to [add the WatsonX keys](https://github.com/ibm-granite-community/granite-snack-cookbook/pull/45#issuecomment-2430055769) to the Github Action environment.

**Comment by adampingel** [comment]
Those are already in place

**Comment by fayvor** [comment]
[#45](https://github.com/ibm-granite-community/granite-snack-cookbook/pull/45) merged

**Comment by fayvor** [comment]
Now we're getting this "token_quota_reached" failure in Agentic_RAG:

```
ApiRequestFailure: Failure during generate. (POST ***ml/v1/text/generation?version=2024-10-14)
Status code: 403, body: {"errors":[{"code":"token_quota_reached","message":"Request of 1 token(s) from quota was rejected","more_info":"https://cloud.ibm.com/apidocs/watsonx-ai"}],"trace":"fd0b0ed54e2cf8b523574b4c3b30a2df","status_code":403}
```

https://github.com/ibm-granite-community/granite-snack-cookbook/actions/runs/11484241158/job/31961540469?pr=46

**Comment by AnnaGutowska** [comment]
@fayvor I am receiving the same error in [this PR](https://github.com/ibm-granite-community/granite-snack-cookbook/pull/47). Is the API key used by the org attached to a free account of watsonx? This is likely the reason for the error.
