### ISSUE TITLE
"snack" version of summarization

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-community/granite-snack-cookbook#4]
Aside from living in the snack cookbook, this ticket represents identifying some data not among the current set of domains we have dedicated cookbooks for and applying summarization to that dataset.  It could (should) be something fun.

**Comment by rawkintrevo** [comment]
so on hold until gen3/lang models come online?

**Comment by adampingel** [comment]
WIP https://github.com/ibm-granite-community/granite-snack-cookbook/pull/13
