### ISSUE TITLE
finalize "snack" version of RAG recipe

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-community/granite-snack-cookbook#6]
What we have in place may very well be final already, but some additional questions before it is sealed:

- Is our prompt aligned with the Granite prompt guidelines?
- Is a single document the right way to downsize the recipe?  (it may be)

**Comment by fayvor** [comment]
> Is a single document the right way to downsize the recipe? (it may be)

The [RAG_with_Langchain](https://github.com/ibm-granite-community/granite-snack-cookbook/blob/main/recipes/RAG/RAG_with_Langchain.ipynb) snack recipe does currently use just one document. (attn @adampingel)

**Comment by fayvor** [comment]
Closing in favor of this more general ticket: [Ensure Optimized Prompts in Snacks](https://github.com/ibm-granite-community/pm/issues/147)
