### ISSUE TITLE
Take advantage of larger context in RAG recipe

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-community/granite-snack-cookbook#83]
As written, this was intended to cover the "Snack" version: https://github.com/ibm-granite-community/granite-snack-cookbook/blob/main/recipes/RAG/RAG_with_Langchain.ipynb

As discussed last week, we may not do anything to this recipe other than bump the version.  Elsewhere in domain-specific cookbooks we may have a better opportunity to showcase the larger context.

**Comment by bjhargrave** [comment]
RAG_with_Langchain will be changing to use the new embedding models. These have a 512 token context length. So we won't be able to chunk the document any larger than it currently is. This will probably true for any RAG recipe which is also updated to use the new embedding models.
